### PR TITLE
Bind events in Channel

### PR DESCRIPTION
**Pull request by welingtonsampaio**
Two new methods
- bind
- unbind

Integrated with ThunderPush welingtonsampaio/thunderpush@8568ea7
#### Send message ( POST )

**URI:** /api/1.0.0/events/event-name/
**BODY:**

``` json
{
  "channel": "channel-name",
  "foo": "bar"
}
```

or 

``` json
{
  "channel": ["first-channel", "second-channel"],
  "foo": "bar"
}
```
#### Javascript binds

``` js
Thunder.subscribe('chat', function(channel){
  channel.bind('message:received', function(data, channel, event){
    console.log('Data:', data);
    console.log('Channel:', channel);
    console.log('Event name:', event);
    console.log('---------------------------------------------');
  });
});

```

### CODE REVIEW

**Comment by jrschumacher** [comment]
@welingtonsampaio since this is specific to thunderpush/thunderpush#40 we need to discuss this first

**Comment by jrschumacher** [comment]
@welingtonsampaio also reviewing this it looks like its not backwards compatible. So we'll need to hold off for a 2.0 release. However, I like the implementation. I'll create a new 2.0 branch and let's work at cleaning up the code as a whole using this new implementation.

One other thing I would like to add is the requirement that `Thunder.connect()` returns an instance of thunderpush so in theory you could connect to multiple thunderpush servers.

**Comment by welingtonsampaio** [comment]
I have a few years experience in coffeescript. Do you think interesting to migrate the Thunder object to a class?

**Comment by jrschumacher** [comment]
Yes I am making it a class but I don't want to convert to CoffeeScript personally. There are some apps where I see CoffeeScript useful but for a small project and smaller community I think it would reduce adoption.

**Comment by welingtonsampaio** [comment]
Okay, so contribute with the javascript in the project and when are ready, I port to coffeescript. So we can achieve the two communities. Do you agree? =)

**Pull request closed without merging**
